// @ts-nocheck
import React,{ useState,useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Sidebar from "../../components/Sidebar";
import Widgets from "../../components/Widgets";
import Post from "../../components/Post";
import { ArrowLeftIcon,} from "@heroicons/react/24/outline";
import { db } from "../../firebase";
import { onSnapshot,doc,query,collection,orderBy } from "firebase/firestore";
import Comment from "../../components/Comment";

export default function PostPage({ newsResults,randomUsersResults }) {
    const router = useRouter();
    const { id } = router.query;
    const [ post,setPost ] = useState(null);
    const [ comments,setComments ] = useState([]);
    useEffect(() => {
        onSnapshot(doc(db,"posts",id),(snapshot) => {
            setPost(snapshot);
        });
    },[ db,id ]);
    useEffect(() => {
        onSnapshot(query(collection(db,"posts",id,"comments"),orderBy("timestamp","desc")),
            (snapshot) => { setComments(snapshot.docs); }
        );
    },[ db,id ]);
    return (
        <div>
            <Head>
                <title>Twitter Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='flex min-h-screen mx-auto'>
                {/* Sidebar */}
                <Sidebar />
                {/*Feed*/}
                <div className='xl:ml-[370px] border-l border-r xl:min-w-[576px] border-gray-200
                    sm:ml-[73px] flex-grow max-w-xl'>

                    <div className='flex py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200 items-center'>
                        <div className="hoverEffect mr-2" onClick={() => router.push("/")}>
                            <ArrowLeftIcon className="h-5" />
                        </div>
                        <h2 className='text-lg sm:text-xl font-bold cursor-pointer'>Tweet</h2>
                    </div>
                    <Post post={post} id={id} />
                    {comments.length > 0 && comments.map((comment) =>
                        <Comment key={comment.id} comment={comment.data()} />
                    )}
                </div>
                {/*Widgets*/}
                <Widgets news={newsResults?.articles} users={randomUsersResults?.results} />

            </main>
        </div>
    );
}



export async function getServerSideProps() {
    const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/technology/au.json")
        .then((res) => res.json());
    const randomUsersResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture")
        .then(res => res.json());
    return {
        props: {
            newsResults,
            randomUsersResults
        }
    };
}